### ISSUE TITLE
[FEATURE] Add anothers kinds of service to pay

### ISSUE THREAD

**Issue by danny920825** [rafrsr/qvapay-wc-gateway#1]
Hi Rafa, can you please add support to https://www.salonbookingsystem.com ??
This can be great to bussines like 
HAIR DRESSERS SALONS
BARBER SHOP
BEAUTY SALONS
SPAS
CAR SHOPS
THERAPISTS
TUTORS
and others...

**Comment by rafrsr** [comment]
This is only a payment gateway for qvapay, a feature like that should be a different plugin, wordpress already have a lot of plugin to do this [https://wordpress.org/plugins/search/booking/](https://wordpress.org/plugins/search/booking/)
